#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Hyperpolarized Carbon-13 Magnetic Resonance Imaging  # The title of the book. Will be placed in the left navbar.
author                      : "Book Editor: Peder Larson"  # The author of the book
copyright                   : "2025"  # Copyright year to be placed in the footer
logo                        : HP_MRI_Book_graphic.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/UCSF-HMTRC/hyperpolarized_mri_book  # Online location of your book
  path_to_book: "" # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar              : <b>PREPRINT FOR EDUCATIONAL USE ONLY</b>
  extra_footer              : Citation - DOI <a href="https://doi.org/10.5281/zenodo.15603048">10.5281/zenodo.15603048</a> # <a href="https://doi.org/10.5281/zenodo.5547020"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.5547020.svg" alt="DOI"></a>  # Will be displayed underneath the footer.
#  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
#  google_analytics_id       : "UA-51903906-1"  # A GA id that can be used to track book views.
